server:
  port: 8082

spring:
  application:
    name: account-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:password}@${DISCOVERY_SERVER:localhost}:8761/eureka