server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: # cấu hình git repository
          uri: https://github.com/luongquoctay87/app-info
          default-label: master
#          username: luongquoctay
#          password: xxxx

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka: # cấu hình eureka client kết nối tới eureka server
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:password}@${DISCOVERY_SERVER:localhost}:8761/eureka